### ISSUE TITLE
get the ccr working for lz4 as a pathfinder project...

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#1]
Let us discuss how this would work for the lz4 filter.

Let us assume no changes in netcdf-c configure or API to support ccr.

We want a cmake and autotools build of lz4. We also want an overall ccr autotools/cmake build, which just launches the lz4 builds.

Do we also want a C/Fortran library? I believe we do. Because Fortran users will have a hard time with the C code needed to handle the filter API in netcdf-c. So we could have a small library in C which provides the a good api for the lz4 filter, and then wrap a Fortran function around that. 

Then, users download and install libccr. They get the lz4 filter, and also the C and Fortran libraries whcih provide calls like: 

```
nc_def_var_lz4(ncid, varid, lz4_level)
nc_inq_var_lz4()

```
Does that make sense?

**Comment by czender** [comment]
That's one way. The API you suggest seems natural for LZ4. Since you are keen on LZ4 let's start with that. I suggest ZStandard second. A primary design goal should be compatibility with Dennis' `nc_def/inq_var_filter()` methodology. CCR should, at a minimum, build/install filters that can be called with that "API" (passing basically an argc of option count and argv of unsigned ints that encode the options). Do you agree this is a minimal requirement? If so, let's fork the LZ4 filter into a CCR lz4/src directory and start to annotate for autotools compatibility (CMake can come later). I see the API you describe above as basically translating parameter counts/values to from the `nc_def/inq_var_filter()` calls. Do you agree? Or suggest your alternative.

**Comment by edwardhartnett** [comment]
Yes, the functions I propose will simply call the filter API with the correct parameters, and provide nice functions to wrap in Fortran.

If we can convince Unidata to support it, these would be the functions I would put in netCDF. Until they, this can serve as a demonstration, and something users like NOAA can turn too immediately to meet severe operational needs.

**Comment by czender** [comment]
Great guerilla programming tactics!
