### ISSUE TITLE
What's up with bitgroom filter parameters

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#130]
Why are there so many filter parameters for bitgroom? I expected one, but there seem to be 5...

```
netcdf tst_eamv1_benchmark_bitgroom_bzip2_gfs_level_4_nsd_3 {
dimensions:
	time = UNLIMITED ; // (1 currently)
	ncol = 48602 ;
	lev = 72 ;
variables:
	float AEROD_v(time, ncol) ;
		AEROD_v:_Storage = "chunked" ;
		AEROD_v:_ChunkSizes = 1, 48602 ;
		AEROD_v:_Filter = "37373,3,4,1,2096103424,2540693168|307,4" ;
		AEROD_v:_Endianness = "little" ;
```

**Comment by edwardhartnett** [comment]
OK, I see this in ccr.c:

```
  /* NB: Internally, the filter requires CCR_FLT_PRM_NBR (=5) elements for cd_value
     However, the user needs to provide only the first element, NSD, since the other
     elements can be and are derived from the dcpl (data_class, datum_size),
     and extra queries of the variable (has_mss_val, mss_val).
     Hence, the netCDF API exposes to the user and requires setting only the 
     minimal number (1) of filter parameters.
     Everything else should be automagical (knock on wood). */ 

```

I will move this comment into the documentation...

**Comment by edwardhartnett** [comment]
I have added this to the docs. The user needs to know this because ncdump shows all five parameters, and it's confusing.

**Comment by edwardhartnett** [comment]
@czender can you just move 4 parameters into the filter code and reduce it to 1?

**Comment by czender** [comment]
Of course I tried to do it with one parameter but the HDF5 interface stymied every approach I tried. Remember, BG is atypical in that it should only apply to floats, and leave everything else untouched. I decided it was better that integer fields not enter the filter at all, or else they would exit with _Filter attributes even though they had not been altered. Therefore, heavy processing needs to be done in the callback functions. And handling _FillValue was all wrapped up in that. Of course there may be a better approach than I found and I would be grateful if you double-checked the approach. However, I do not consider 5 values in cd_params untenable, because it's all hidden from the user. Right now BG works for floats, doubles, heeds _FillValue, and does not touch other variables. It is ready for prime-time, even if it could be improved in a future release.
