### ISSUE TITLE
Should ccr.h define any API for disabled filters?

### ISSUE THREAD

**Issue by czender** [ccr/ccr#131]
`ccr.h` now has, e.g.,

```
    /* Library prototypes... */
    int nc_def_var_bzip2(int ncid, int varid, int level);
    int nc_inq_var_bzip2(int ncid, int varid, int *bzip2p, int *levelp);
``` 

Should this instead be

```
#if CCR_HAS_BZIP2
    /* Library prototypes... */
    int nc_def_var_bzip2(int ncid, int varid, int level);
    int nc_inq_var_bzip2(int ncid, int varid, int *bzip2p, int *levelp);
#endif
``` 

and similarly for the other filters and in the `ccr.c` definition file? 

An external program using the CCR API must bind to the symbols at compile time. Otherwise...well, either breakage during link time or an eventual 'filter not found'  error I suppose. What thinkest thou? Yes, client libraries (e.g., NCO which I am hookingu up to CCR  as I type) can use the `CCR_HAS_...` tokens in `ccr_meta.h` to workaround this issue, yet is that what we want clients to do?

**Comment by edwardhartnett** [comment]
Yes, this is what we want users to do.

We do not want to use CCR_HAS_BZIP2 in the header, because that symbol is from config.h and that must not be included in ccr.h.

Extra prototypes are not a problem and will not cause a problem. THe actually function nc_def_var_bzip2 will not be in the library unless it has been built, so the user will get a link error if they try to link to a ccr library that was not built with bzip2. The remedy for the user is to use ccr_meta.h, or to look for the existence of the function, or to just know what has been built.
