### ISSUE TITLE
Can I read bitgroomed data without the bitgroom filter?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#135]
Once I have applied the bitgroom filter, do I also need to have it to read the data?

Seems like I should not need it, but I suspect the code, as now written, requires it. Because ncdump shows the bitgroom filter has been applied to the data, so it will be required when the data is read, even if it does nothing. Right?

Maybe that can't be avoided, but we need to document it one way or the other.

**Comment by czender** [comment]
One must understand that BG is useless (as a compressor) until/unless followed by subsequent lossless compression. Hence we can assume that BG users (via CCR) have the CCR, and so will have access to all its lossless compressors. That said, non-floating point variables do not go through the filter, and so the BG filter is not needed to read them, but the lossless compression filters are.

**Comment by czender** [comment]
As a followup, the way to avoid needing the filter to read BG data is to do BG with the native NCO BG interface, `--ppc=nsd`. As written in the CCR, BG adds filter parameters to floating point variables. One potential way to solve this issue is to create combined filters, e.g., BGZstd and BGBzip2, whose filter code first uses the (currently) NCO-native BG routines to do the BG (i.e., the prefilter) and then calls the CCR Zstd/Bzip2 filter as appropriate. This would require new filter IDs for these "dual-filters". That would make possible having quantized data without any _Filter parameters.

**Comment by edwardhartnett** [comment]
For this release, we can just document that the bitgroom filter must be present for reading as well as writing.

Since everyone already has gzip, a way of bit grooming without requiring a read filter would be nice. However, we can't have it all.

**Comment by edwardhartnett** [comment]
I have added to the docs...
