### ISSUE TITLE
What to do with Charlie's new Zstandard filter implementation?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#137]
As discussed in #136 Charlie re-wrote the Zstandard filter. What should be done here? He is reusing the Zstandard filter ID. Is that OK or should there be a new one?

I sent an email to Elena and Allen from the HDF group to ask what they think.

**Comment by byrnHDF** [comment]
My only concern about the filter value is can this version read the a dataset compressed with the older version and more importantly, can the older zstandard read a new dataset. I think that second situation would determine the direction. 

Allen

**Comment by edwardhartnett** [comment]
Good question! @czender do you know the answer?

**Comment by edwardhartnett** [comment]
> Elena Pourmal via hdftest.onmicrosoft.com 
> 7:37 AM (8 minutes ago)
> to me, Allen, Charles
> 
> Ed,
> 
> I would strongly recommend to contact Barbara and register new ID if there is any incompatibility in two implementations, fie example, data written by the new filter cannot be decoded by the old one. 
> 
> Merry Christmas to everyone!
> 
> Elena

**Comment by czender** [comment]
@edwardhartnett I do not know for sure because I have not tested this. Like I said, the CCR Zstandard accepts a wider range of compression levels (inluding negative levels) and is a superset of the original filter so should be able to decompress anything the other compresses. Also, the older filter uses functions that are deprecated (though still present) in libzstd.a. I think that the older filter can decompress anything the CCR filter compresses, especially if the old filter is linked to a current libzstd.a, though it's possible I'm wrong. This should be tested.

**Comment by terrelln** [comment]
> My only concern about the filter value is can this version read the a dataset compressed with the older version and more importantly, can the older zstandard read a new dataset. I think that second situation would determine the direction.

Assuming both filters read/write the zstandard format without any additional bytes, they will be compatible. The zstd format is fixed since version v0.8.1, so all zstd versions from v0.8.1 onward can read data produced by any other version from v0.8.1 onward. E.g. v0.8.1 can read data produced by v1.4.8, and v1.4.8 can read data produced by v0.8.1, no matter which parameters are used.

However, if this filter adds extra bytes, like its own header, I can't speak to that.

> Also, the older filter uses functions that are deprecated (though still present) in libzstd.a

That is fine from a compatibility standpoint, they still produce the same format. But, eventually they will be removed from the library.

**Comment by czender** [comment]
Thanks @terrelin. The CCR Zstandard filter does nothing special, and so should behave compatibly as you outline. Still, the only way to know for sure is to test.

**Comment by edwardhartnett** [comment]
We are planning on release on Monday. Can we test before then?

What would constitute a test? Being able to read one such file correctly? Can we use the old filter to create a small test file, then we can add that test file to CCR and make sure we can read it?

**Comment by czender** [comment]
I do not have the bandwidth the test this in the near future. We can ask for a new filter ID or trust that the compatibility with the old filter is good based on the above comments. I am inclined to trust the compatibility of Zstandard rather than introduce a new filter. One minor problem is that the HDF5 page for Zstandard would continue to point to the HDF registered filter.

**Comment by edwardhartnett** [comment]
OK, we will proceed with this and if we find we have made an error, we will just have to cope with it then...
