### ISSUE TITLE
adjust to changes in netcdf-c WRT order of filters

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#162]
We have recently discovered an inconsistency in the order of how filters are perceived by the netcdf-c API. (See https://github.com/Unidata/netcdf-c/issues/1923).

Once this is fixed in netcdf-c master, I believe our nc_inq_var_bitgroom() function will start failing tests and will need to be fixed.

I believe all this will happen before the next netcdf-c release.

**Comment by czender** [comment]
With the current netCDF-C master,` tst_zstandard` fails for me in the multi-filter test. Line 234 of `tst_zstandard.c` calls `nc_inq_var_bitgroom()`. The `nc_inq_var_filter_ids()` call at ccr.c line 440 for the double filtered (BG and Zstd) test variable appears to return `nfilters=0` instead of `nfilters=2`. I am working on branch `csz_bg_mlt_inq`.

**Comment by edwardhartnett** [comment]
Umm, isn't the master building with netCDF master and working in GitHub actions?

**Comment by czender** [comment]
Indeed. The multi-filter code in all the `nc_var_inq_XXX() ` functions would continue searching all filters even after finding the desired filter, and, due to its contruction, overwrite the properties of the first filter found with the results of the second test looked for (and not found). The bug showed up when I addingn testing of the results of the BG properties within the Zstandard multi-filter test. All now fixed via #164.
