### ISSUE TITLE
what the heck is up with the lz4 filter?

### ISSUE THREAD

**Issue by edwardhartnett** [ccr/ccr#20]
As detailed in PR #19 the LZ4 filter more than doubled the size of the test data. So what the heck? No one wants that!

Some pure HDF5 testing would be useful in the hdf5_plugins project to demonstrate that the LZ4 filter works correctly (i.e. actually compresses data).

**Comment by edwardhartnett** [comment]
@czender this is the issue that worries me the most.

I'm going to take another look at this tomorrow. Have you achieved actual compression with the LZ4 filter in the past?

**Comment by czender** [comment]
The command line version `lz4` works as expected for me. The CCR version has always increased data size for me. Not sure why either. BTW I learned a few weeks ago that the author of LZ4 is Yann Collet. He subsequently developed Zstandard, which works fine in the CCR, and beats LZ4 in every category of benchmark I have seen (I havn't looked hard at this).

**Comment by edwardhartnett** [comment]
Ah ha! That's a good thing. So perhaps we take out LZ4 if we can't figure that out and just go with ZStandard.

**Comment by edwardhartnett** [comment]
OK, I'm going to take out LZ4 for now. Up from the ashes, up from the ashes, grow the roses of success! https://www.youtube.com/watch?v=GND10sWq0n0

**Comment by czender** [comment]
The LZ4 filter seems to have implemented "streaming mode" rather than the "single pass" method I used in Zstandard. A single pass is simpler to implement. I wonder if we looked more carefully at the LZ4 library we would find single-pass functions so that the filter could be simplified to look more like Zstandard. I agree though that it should be disabled by default until it gives a compression ratio closer to advertised. Otherwise we would just be giving LZ4 a bad name.

**Comment by edwardhartnett** [comment]
I have disabled LZ4 in the configure.ac. If uncommented, these lines will cause it to be built:

```
dnl AC_MSG_CHECKING([whether LZ4 filter library should be built and installed])
dnl AC_ARG_ENABLE([lz4],
dnl               [AS_HELP_STRING([--disable-lz4],
dnl                               [Disable the build and install of lz4 filter library.])])
dnl test "x$enable_lz4" = xno || enable_lz4=yes
dnl AC_MSG_RESULT($enable_lz4)

```
